# Generated by Django 2.2 on 2019-05-05 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190429_1516'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='task_list',
            new_name='tasklist',
        ),
    ]
